name: release

on:
  push:
    tags: ['v*.*.*']

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  release:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
